# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZDaP2SrDkoztWb3fDV2T_4wWwCoJP8fE
"""

# harsad number
n=int(input("enter number"))#43
p=n
sum1=0
while(n>0):
  v=n%10
  sum1+=v
  n=n//10
if(p%sum1==0):
    print("harshad number")
else:
    print("not harsad number")

#automorphic number
num=int(input("enter a number"))
len1=len(str(num))
square=num**2
sum=0
digit=square%pow(10,len1)
if num==digit:
  sum+=num
  print("automorpic number")
else:
  print("not automorpioc number")
print(sum)

def palendrom (p):
  rev=str(p)[::-1]
  if p==int(rev):
    return "palendrom"
  else:
    return "not a palendrom"
p=int(input())
result=palendrom(p)
print(result)

#
dict1={1:1,2:3,3:4}
dict1[1]=10
print(dict1)

#
dict1={1:42,2:4,7:2}
dict1.items()

#
dict1={1:2 ,2:3,3:6}
dict1.keys()

f = open("demofile.txt","a")
f.write("Now the file has more contest!")
f.close()
f=open("demofile2. bnu ")